### ISSUE TITLE
Which licence?

### ISSUE THREAD

**Issue by stefsmeets** [SCM-NV/pyZacros#56]
Hi all,

This code seems to have multiple licence declarations:

1. Apache 2.0 in [setup.py](https://github.com/SCM-NV/pyZacros/blob/master/setup.py)
2. Dual licence in [LICENCE](https://github.com/SCM-NV/pyZacros/blob/master/LICENSE)

Which one is correct?

**Comment by nfaguirrec** [comment]
Now the license is set in both files as LGPLv3. In particular, in the LICENCE file it is explicit the there is a BSD3 exception for SCM. Thanks!
