### ISSUE TITLE
Empty site!

### ISSUE THREAD

**Issue by perasperadastra** [SCM-NV/pyZacros#69]
Hello,
Im sure that this option should  be somewhere in the code, but how we can add the "&" option to build lateral interacctions?
Thanks.

**Comment by nfaguirrec** [comment]
Hi! Unfortunately, this option is not still available, but we will try to include it soon. Thanks for your interest in pyZacros.

**Comment by nfaguirrec** [comment]
It looks like it was not so hard to implement this option. Please, take a look at the new example (examples/LangmuirHinshelwood/LangmuirHinshelwood.py) and let me know if it works for you. Thanks!

**Comment by perasperadastra** [comment]
Hi! Thanks for the fast answer and improve. Despite i will like to say it works, it doen't for more complicated systems. The las error trace ist AttributeError: 'Cluster' object has no attribute 'is_adsorbed'.
Thanks for your attention!.

**Comment by nfaguirrec** [comment]
Hi! If you send me a simplified version of your failing example, I can take a look at it and try to fix this issue. Thanks!

**Comment by perasperadastra** [comment]
Unfortunately I change my experiments and I am not currently using this option. But thanks for your attention!
