### ISSUE TITLE
Problems in the generation of state_input.dat

### ISSUE THREAD

**Issue by mbracconi** [SCM-NV/pyZacros#72]
Hi,

When the `initial_state` option is employed and a lattice state from an another simulation is used, pyZacros generates the `state_input.dat` file. However, there are problems when bidentate (and I guess multi-dentate) species are present in the lattice.
The simulation crashes during the loading of the simulation with the following error:
`Error code 5004 from state_parser_module: seed_on_sites keyword must be followed by a species name (string) and nspecdent integers in state_input.dat.`

This is due to fact that the `state_input.dat` generated by pyZacros list for multi-dentate species the following text:
`seed_on_sites O2** 306`
However, Zacros expects:
`seed_on_sites O2** site1 site2`
Or more generally as many sites as dentates on the surface.

Thanks

**Comment by nfaguirrec** [comment]
Hi Mauro! This is interesting. I wrote a test for this case, well only for a bidentate case, and it works well (see tests/test_LatticeInitialState.py), surely I forgot something. Could you please make a simple example script reproducing the error you found? Thanks!

**Comment by nfaguirrec** [comment]
Hi Mauro! Could you please try again? I think I fixed the bug. Thanks!
