### ISSUE TITLE
variant option in clusters is missing

### ISSUE THREAD

**Issue by mbracconi** [SCM-NV/pyZacros#73]
Hi,

I noticed that the option `variant` is missing in the cluster definition. This strongly affect the `load_external` option since the `energetic_input.dat` is not parsed correctly but no error is provided resulting in weird simulation behavior

Mauro

**Comment by nfaguirrec** [comment]
Thanks! That's correct, the variant option is not supported yet in the cluster's definition. However, I have included an Exception which is raised if the variant keyword is found in the ``energetics_input.dat`` file. In that case, the message is as follows:
```
Exception: ZacrosJob.__recreate_energetics_input. Option 'cluster%variant' is not supported yet!
```
