### ISSUE TITLE
Error using load_external function

### ISSUE THREAD

**Issue by lopeztarifa** [SCM-NV/pyZacros#79]
Hi @nfaguirrec, 

I upload the files we discussed yesterday. They are regular Zacros input files that crash while using the load_external function.

This script:
```

import scm.pyzacros as pz

pz.init()
inputs = './'
input_job = pz.ZacrosJob.load_external(inputs)

pz_job = pz.ZacrosJob(lattice=input_job.lattice, \
                      mechanism=input_job.mechanism, \               
                      cluster_expansion=input_job.cluster_expansion)

results = pz_job.run()
```

gives error, because PLAMS (?) prints some additional info in the simulation_input.dat file

```
molar_fraction:
               O2:      0.0
               CO:      0.0
               CO2:     0.0
run:    <empty Settings>
keep:   all
link_files:     True
pickle:         True
pickle_protocol:        -1
runscript:
          shebang:      #!/bin/sh
          stdout_redirect:      False
save:   all

n_gas_species    3
gas_specs_names    
```

Can you take a look? Thank you! 

[example.tar.zip](https://github.com/SCM-NV/pyZacros/files/10081350/example.tar.zip)

**Comment by nfaguirrec** [comment]
Hi Pablo,

The error happens because the parameter ``settings`` is missed in the ZacrosJob constructor. If you do the following, you will get the expected result:
```
pz_job = pz.ZacrosJob(settings=input_job.settings, \
                      lattice=input_job.lattice, \
                      mechanism=input_job.mechanism, \
                      cluster_expansion=input_job.cluster_expansion)

```
However, this example highlights an essential aspect that must be addressed. I'll make the argument "settings " required rather than optional. 

Best,
Nestor

**Comment by lopeztarifa** [comment]
great, thanks!
